package AsiPriceData;

import java.util.ArrayList;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;


@JsonIgnoreProperties(ignoreUnknown = true)
public class ListOfModelDetails{
    @JsonProperty("DOOR_OPENING_WIDTH_HEIGHT_PRICE") 
    public ArrayList<Object> dOOR_OPENING_WIDTH_HEIGHT_PRICE;
    @JsonProperty("MOTOR_COVER") 
    public ArrayList<MOTORCOVER> mOTOR_COVER;
    @JsonProperty("MOTOR_COVER_COLOR") 
    public ArrayList<MOTORCOVERCOLOR> mOTOR_COVER_COLOR;
    @JsonProperty("DRUM_HOOD_DRUM_FASCIA") 
    public ArrayList<DRUMHOODDRUMFASCIum> dRUM_HOOD_DRUM_FASCIA;
    @JsonProperty("DRUM_HOOD_DRUM_FASCIA_COLOR") 
    public ArrayList<DRUMHOODDRUMFASCIACOLOR> dRUM_HOOD_DRUM_FASCIA_COLOR;
    @JsonProperty("EZX_BLOWER_UNIT_BERNER_FINISH") 
    public ArrayList<EZXBLOWERUNITBERNERFINISH> eZX_BLOWER_UNIT_BERNER_FINISH;
    @JsonProperty("STAINLESS_STEEL_INNER_AND_OUTER_SIDE_GUIDES") 
    public ArrayList<STAINLESSSTEELINNERANDOUTERSIDEGUIDE> sTAINLESS_STEEL_INNER_AND_OUTER_SIDE_GUIDES;
    @JsonProperty("SIDE_GUIDE_COVER_COLOR") 
    public ArrayList<SIDEGUIDECOVERCOLOR> sIDE_GUIDE_COVER_COLOR;
    @JsonProperty("STAINLESS_STEEL_SHAFT_DRUMS_AND_BEARINGS") 
    public ArrayList<STAINLESSSTEELSHAFTDRUMSANDBEARING> sTAINLESS_STEEL_SHAFT_DRUMS_AND_BEARINGS;
    @JsonProperty("STAINLESS_STEEL_HEAD_PLATES") 
    public ArrayList<STAINLESSSTEELHEADPLATE> sTAINLESS_STEEL_HEAD_PLATES;
    @JsonProperty("DOOR_STYLE") 
    public ArrayList<DOORSTYLE> dOOR_STYLE;
    @JsonProperty("VISION_AND_SCREEN") 
    public ArrayList<VISIONANDSCREEN> vISION_AND_SCREEN;
    @JsonProperty("STAINLESS_STEEL_PACKAGE") 
    public ArrayList<STAINLESSSTEELPACKAGE> sTAINLESS_STEEL_PACKAGE;
    @JsonProperty("HEAVY_IMPACT_ZONE_BUG_SCREEN") 
    public ArrayList<HEAVYIMPACTZONEBUGSCREEN> hEAVY_IMPACT_ZONE_BUG_SCREEN;
    @JsonProperty("MANUAL_CHAIN_HOIST") 
    public ArrayList<MANUALCHAINHOIST> mANUAL_CHAIN_HOIST;
    @JsonProperty("FORE_FRAME") 
    public ArrayList<FOREFRAME> fORE_FRAME;
    @JsonProperty("INSULATING_CURTAIN") 
    public ArrayList<INSULATINGCURTAIN> iNSULATING_CURTAIN;
    @JsonProperty("EGRESS_CURTAIN") 
    public ArrayList<EGRESSCURTAIN> eGRESS_CURTAIN;
    @JsonProperty("SEALED_BOTTOM_BAG") 
    public ArrayList<SEALEDBOTTOMBAG> sEALED_BOTTOM_BAG;
    @JsonProperty("ADDITIONAL_PHOTOCELL_HEIGHT") 
    public ArrayList<ADDITIONALPHOTOCELLHEIGHT> aDDITIONAL_PHOTOCELL_HEIGHT;
    @JsonProperty("LOGO_AND_PRINT_LOCATION") 
    public ArrayList<LOGOANDPRINTLOCATION> lOGO_AND_PRINT_LOCATION;
    @JsonProperty("LOGOS_AND_PRINTS_SIZE") 
    public ArrayList<LOGOSANDPRINTSSIZE> lOGOS_AND_PRINTS_SIZE;
    @JsonProperty("CONTROL_PANEL") 
    public ArrayList<CONTROLPANEL> cONTROL_PANEL;
    @JsonProperty("INCOMING_POWER") 
    public ArrayList<INCOMINGPOWER> iNCOMING_POWER;
    @JsonProperty("LINE_LOAD_REACTOR") 
    public ArrayList<LINELOADREACTOR> lINE_LOAD_REACTOR;
    @JsonProperty("ADDITIONAL_PHOTOCELL") 
    public ArrayList<ADDITIONALPHOTOCELL> aDDITIONAL_PHOTOCELL;
    @JsonProperty("HIGH_SPEED_OPENING") 
    public ArrayList<HIGHSPEEDOPENING> hIGH_SPEED_OPENING;
    @JsonProperty("INTELLI_EDGE_DYNALOGIX_5") 
    public ArrayList<INTELLIEDGEDYNALOGIX5> iNTELLI_EDGE_DYNALOGIX_5;
    @JsonProperty("PNEUMATIC_BOTTOM_EDGE_WITH_SWITCH") 
    public ArrayList<PNEUMATICBOTTOMEDGEWITHSWITCH> pNEUMATIC_BOTTOM_EDGE_WITH_SWITCH;
    @JsonProperty("EXTENDED_ZIPPER") 
    public ArrayList<EXTENDEDZIPPER> eXTENDED_ZIPPER;
    @JsonProperty("STAINLESS_STEEL_ZIPPER_CABLE") 
    public ArrayList<STAINLESSSTEELZIPPERCABLE> sTAINLESS_STEEL_ZIPPER_CABLE;
    @JsonProperty("REDUCED_LINTEL") 
    public ArrayList<REDUCEDLINTEL> rEDUCED_LINTEL;
    @JsonProperty("EXTENDED_HEADER_FOR_BERNER_UNIT") 
    public ArrayList<EXTENDEDHEADERFORBERNERUNIT> eXTENDED_HEADER_FOR_BERNER_UNIT;
    @JsonProperty("EZX_BERNER_BLOWER_UNIT") 
    public ArrayList<EZXBERNERBLOWERUNIT> eZX_BERNER_BLOWER_UNIT;
    @JsonProperty("INTERLOCK_OPTIONS") 
    public ArrayList<INTERLOCKOPTION> iNTERLOCK_OPTIONS;
    @JsonProperty("EZX_BERNER_BLOWER_UNIT_VOLTAGE") 
    public ArrayList<EZXBERNERBLOWERUNITVOLTAGE> eZX_BERNER_BLOWER_UNIT_VOLTAGE;
    @JsonProperty("EZX_BLOWER_UNIT_BERNER_REMOTE_WALL_SWITCH_BLOWER_HEAT_ON_OFF") 
    public ArrayList<EZXBLOWERUNITBERNERREMOTEWALLSWITCHBLOWERHEATONOFF> eZX_BLOWER_UNIT_BERNER_REMOTE_WALL_SWITCH_BLOWER_HEAT_ON_OFF;
    @JsonProperty("EZX_BLOWER_UNIT_BERNER_TIME_DELAY") 
    public ArrayList<EZXBLOWERUNITBERNERTIMEDELAY> eZX_BLOWER_UNIT_BERNER_TIME_DELAY;
    @JsonProperty("EZX_BLOWER_UNIT_BERNER_INDUSTRIAL_THERMOSTAT_SWITCH") 
    public ArrayList<EZXBLOWERUNITBERNERINDUSTRIALTHERMOSTATSWITCH> eZX_BLOWER_UNIT_BERNER_INDUSTRIAL_THERMOSTAT_SWITCH;
    @JsonProperty("CRATING") 
    public ArrayList<CRATING> cRATING;
    @JsonProperty("SPECIAL_FUNCTIONS") 
    public ArrayList<SPECIALFUNCTION> sPECIAL_FUNCTIONS;
    @JsonProperty("SPF") 
    public ArrayList<SPF> sPF;
    @JsonProperty("ADDITIONAL_REINSERTION_POINTS") 
    public ArrayList<ADDITIONALREINSERTIONPOINT> aDDITIONAL_REINSERTION_POINTS;
    @JsonProperty("DOOR_LOCATION") 
    public ArrayList<DOORLOCATION> dOOR_LOCATION;
    @JsonProperty("MOTOR_LOCATION") 
    public ArrayList<MOTORLOCATION> mOTOR_LOCATION;
    @JsonProperty("FIRST_PHOTOCELL_HEIGHT") 
    public ArrayList<FIRSTPHOTOCELLHEIGHT> fIRST_PHOTOCELL_HEIGHT;
    @JsonProperty("CURTAIN_FABRIC_COLOR") 
    public ArrayList<CURTAINFABRICCOLOR> cURTAIN_FABRIC_COLOR;
    @JsonProperty("BOTTOM_BAG_CURTAIN_COLOR") 
    public ArrayList<BOTTOMBAGCURTAINCOLOR> bOTTOM_BAG_CURTAIN_COLOR;
    @JsonProperty("SIDE_GUIDE_COVER") 
    public ArrayList<SIDEGUIDECOVER> sIDE_GUIDE_COVER;
    @JsonProperty("ESCAPE_SIDE_GUIDES") 
    public ArrayList<ESCAPESIDEGUIDE> eSCAPE_SIDE_GUIDES;
    @JsonProperty("ADVANCED_DOUBLE_LIPPED_HORIZONTAL_PROFILE_SEAL") 
    public ArrayList<ADVANCEDDOUBLELIPPEDHORIZONTALPROFILESEAL> aDVANCED_DOUBLE_LIPPED_HORIZONTAL_PROFILE_SEAL;
    @JsonProperty("SLIMLINE_SIDE_PLATES_NO_HOLES") 
    public ArrayList<SLIMLINESIDEPLATESNOHOLE> sLIMLINE_SIDE_PLATES_NO_HOLES;
}
